name:                gsdFlow
version:             0.1.0.0
github:              "githubuser/gsdFlow"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gsdFlow#readme>

dependencies:
  - base >= 4.7 && < 5
  - scotty == 0.11.2
  - uuid
  - aeson
  - attoparsec
  - time
  - async
  - eventstore == 1.1.6
  - text
  - containers
  - hslogger
  - bytestring
  - foundation
  - streamly == 0.5.2
  - random
  - free
  - transformers == 0.5.5.0
  - safe
library:
  source-dirs: src
ghc-options:
  -fwarn-tabs
  -fwarn-unused-imports
  -fwarn-missing-signatures
  -fwarn-incomplete-patterns


executables:
  gsd-sandbox:
    main:                Sandbox.hs
    source-dirs:         app
    ghc-options:
    - -main-is Sandbox
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
  gsd-api:
    main:                Api.hs
    source-dirs:         app
    ghc-options:
    - -main-is Api
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
  gsd-command-manager:
    main:                CommandProcessingManager.hs
    source-dirs:         app
    ghc-options:
    - -main-is CommandProcessingManager
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow

tests:
  gsdFlow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
    - hspec == 2.5.5
    - QuickCheck
    - aeson
    - generic-arbitrary
    - quickcheck-instances
    - aeson-qq
    - generic-random
    - wreq >= 0.5.2.1
