name:                gsdFlow
version:             0.1.0.0
github:              "githubuser/gsdFlow"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gsdFlow#readme>

dependencies:
  - base >= 4.7 && < 5
  - uuid == 1.3.13
  - aeson == 1.4.2.0
  - attoparsec == 0.13.2.2
  - time == 1.8.0.2
  - async == 2.2.1
  - eventstore == 1.2.0
  - text == 1.2.3.1
  - containers
  - hslogger == 1.2.12
  - bytestring == 0.10.8.2
  - foundation == 0.0.21
  - streamly == 0.5.2
  - random == 1.1
  - free == 5.1
  - transformers == 0.5.5.0
  - safe == 0.3.17
  - servant-server == 0.15
  - servant-client == 0.15
  - servant-pipes == 0.15
  - servant == 0.15
  - http-client == 0.5.14
  - lens == 4.17
  - lens-aeson == 1.0.2
  - pipes == 4.3.9
  - wai == 3.2.1.2
  - warp == 3.2.25
  - byline == 0.3.2.0
library:
  source-dirs: src
ghc-options:
  -fwarn-tabs
  -fwarn-unused-imports
  -fwarn-missing-signatures
  -fwarn-incomplete-patterns


executables:
  gsd-read-streaming-api:
    main:                Executables.hs
    source-dirs:         app
    ghc-options:
    - -main-is Executables.gsdReadStreamingApi
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
  gsd-monitoring-streaming-api:
    main:                Executables.hs
    source-dirs:         app
    ghc-options:
    - -main-is Executables.gsdMonitoringStreamingApi
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
  gsd-write-client-cli:
    main:                Executables.hs
    source-dirs:         app
    ghc-options:
    - -main-is Executables.gsdWriteClientCommandLineInterface
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
  gsd-write-api:
    main:                Executables.hs
    source-dirs:         app
    ghc-options:
    - -main-is Executables.gsdWriteApi
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
  gsd-write-command-consumption-streamer:
    main:                Executables.hs
    source-dirs:         app
    ghc-options:
    - -main-is Executables.gsdCommandConsumptionStreamer
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow

tests:
  gsdFlow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsdFlow
    - hspec == 2.5.5
    - QuickCheck
    - aeson
    - generic-arbitrary
    - quickcheck-instances
    - aeson-qq
    - generic-random
    - wreq >= 0.5.2.1
